#!perl

# Extracts the unique words from the given text
# Usage: perl -w words.pl SalesForceClasses.txt >CaseCleaner.SalesForceClasses.cs
# Written by Y [25-06-18]

use strict;
use warnings;

my %count;
#my @blacklist = ("ANY", "APEX_OBJECT", "CURRENCY", "LIST"); # let's avoid these
#my %list = map { $_ => 1 } @blacklist;

while (<>) {
	while (/([a-zA-Z]([\-\']?[\w]+)*)/g) { 
		$count{$1}++ if length($1) > 1 && uc($1) ne $1; # !exists($list{$1})
	}
}

# report statistics
#foreach my $str (sort keys %count) {
#    printf "%-31s %s\n", $str, $count{$str};
#}

print "using System;
using System.Collections.Generic;

namespace ApexSharpDemo.CaseClean
{
    public partial class CaseCleaner
    {
        // generated by $0
        public static HashSet<string> SalesForceNames { get; } = new HashSet<string>(new[]
        {";

# generate C# list
foreach my $str (sort keys %count) {
    printf "
            %-54s // %s", "\"" . $str . "\",", $count{$str};
}

print "
        }, StringComparer.InvariantCultureIgnoreCase);
    }
}
";
