global without sharing class Manager
{
    //closeout Invoices to Payout the amount
    public static void closeOutInvoices()
    {
        /*
        }
        else
        {
        if(paymentCaseDetails != null)
        paymentCaseDetails = setCaseDetails(paymentCaseDetails, 'No unpaid invoices found ', 'In Review', true, null, paymentCaseDetails.paymentConfirmationNumber);
        return;
        }
        */
    }
}
