namespace ApexParser.MetaClass
{
    public enum SyntaxType
    {
        NotFound,
        Accessor,
        Annotation,
        Block,
        BreakStatement,
        Class,
        ClassMember,
        Constructor,
        DoStatement,
        EnumMember,
        Enum,
        Field,
        ForStatement,
        ForEachStatement,
        IfStatement,
        Method,
        Parameter,
        Property,
        Statement,
        Type,
        VariableDeclaration,
        VariableDeclarator,
        WhileStatement,
    }
}