public class ClassNoApex {


    // Any methods in the NoApex name space will be commented out.
    public static void MethodOne()
    {
        System.Debug('Jay');
        //:NoApex NoApex.Console.WriteLine("Jay");
    }

    // Method Name staring with NoApex will be uncommented in C#
    //:NoApex public static void NoApexMethodTwo()
    //:NoApex {
    //:NoApex     NoApex.Console.WriteLine("Jay");
    //:NoApex }
}